// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Duality Scripting Android runtime")]
[assembly: AssemblyDescriptionAttribute("Android runtime for Scripting on Duality dependencies")]
[assembly: AssemblyProductAttribute("DualityScriptingAndroid")]
[assembly: AssemblyVersionAttribute("0.2")]
[assembly: AssemblyFileVersionAttribute("0.2")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.2";
    }
}
